### ISSUE TITLE
Extend The Profanity List?

### ISSUE THREAD

**Issue by jackcsk** [mofodojodino/ProfanityFilter#12]
The current implementation loads the profanities from the config/profanities.php.
Suggest to add the option to load the list by passing in variable, so that users can add / manage the profanity list from their application (e.g. load from db)

**Comment by mofodojodino** [comment]
Hi @jackcsk,

Thanks for the suggestion but you might find you can already do that - please check out https://github.com/mofodojodino/ProfanityFilter/blob/develop/src/mofodojodino/ProfanityFilter/Check.php#L151-L153 as you can pass your own profanity file in which will override the standard one.

If you would like to pass in an array instead of a file I'm happy to except a pull request with the changes.

Cheers
Dino

**Comment by jackcsk** [comment]
Thx @mofodojodino . I've submitted the pull request.
